---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: RXhhbXBsZVVzZXJuYW1l==        # Base64 encoded 'ExampleUsername'
  password: RXhhbXBsZV9IYXJkcEBzc3dvcmQ=  # Base64 encoded 'Example_Hardp@ssword'
