services:
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    ports:
      - '82:5173'
    volumes:
      - ./mineCode:/mnt:rw

  web3:
    restart: on-failure
    build: ./web
    hostname: web3
    ports:
      - '83:5173'
    volumes:
      - ./mineCode:/mnt

  nginx:
    build: ./nginx
    ports:
      - '81:81'
    depends_on:
      - web2
      - web3
